version: '3'

services:
  aws:
    image: localstack/localstack:latest
    ports:
      - '4563-4584:4563-4584'
      - '8055:8080'
    container_name: aws
    environment:
      - SERVICES=s3,dynamodb

  aws-init:
    image: aws-init
    build:
      context: resources/aws-init
    container_name: aws-init
    depends_on:
      - aws
    environment:
      - AWS_DEFAULT_REGION=
      - S3_BUCKET=demobucket

  snapshot-sender:
    image: snapshot-sender
    build:
      context: .
    container_name: snapshot-sender
    depends_on:
      - dks
      - mock-nifi
    environment:
      - CORRELATION_ID=123
      - TOPIC_NAME=db.core.claimant

  snapshot-sender-no-exports:
    image: snapshot-sender
    build:
      context: .
    container_name: snapshot-sender-no-exports
    depends_on:
      - mock-nifi
    environment:
      - CORRELATION_ID=321
      - TOPIC_NAME=db.database.empty
      - ADDITIONAL_SPRING_ACTIVE_PROFILES=noOpReader

  dks:
    image: dks
    ports:
      - 8091:8443
      - 8101:8080
    build:
      context: resources
      dockerfile: Dockerfile_dks
    container_name: dks
    command:
      --spring.main.banner-mode=off
      --logging.level.root=INFO
      --s3.service.endpoint=http://aws:4566
      --server.environment_name=local
    environment:
      - SPRING_PROFILES_ACTIVE=STANDALONE,SECURE,LocalAWS
      - SPRING_CONFIG_LOCATION=application-dks-secure.properties

  mock-nifi:
    image: mock-nifi
    build:
      context: resources
      dockerfile: Dockerfile_mock_nifi
    ports:
      - "5443:5443"
    volumes:
      - shared-volume:/data/output
    container_name: mock-nifi
    environment:
      KEYSTORE_PASSWORD: changeit
      TRUSTSTORE_PASSWORD: changeit
      TLS_KEY_PASSWORD: changeit
      TLS_KEY_ID: cid
      TLS_CERT_ID: self
      TLS_CACERT_ID: mock-nifi

  sender-integration-test:
    image: sender-integration-test:latest
    build:
      context: .
      dockerfile: resources/Dockerfile_sender_integration
    container_name: sender-integration-test
    volumes:
      - shared-volume:/data/output
    depends_on:
      - mock-nifi
    command: "gradle --rerun-tasks integration"

volumes:
  shared-volume:
